version: '2'

services:

  graylog:
    image: graylog2/allinone
    ports:
      - 9000:9000
      - 12201:12201
      - 12201:12201/udp
    volumes:
      - ./graylog/logs:/var/log/graylog
    networks:
      common_network:
        aliases:
          - graylog

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      common_network:
        aliases:
          - redis
    depends_on:
      - graylog

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data_dir:/data/db
    networks:
      common_network:
        aliases:
          - mongodb

  solr:
    image: solr
    ports:
      - "8983:8983"
    volumes:
      - ./solr-cores:/opt/solr/server/solr
    networks:
      common_network:
        aliases:
          - solr

  web:
    build:
      context: web-service
    image: web
    volumes:
      - ./web-service:/var/www/site
    ports:
      - "80:80"
    networks:
      common_network:
        aliases:
          - web
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
    depends_on:
      - redis
      - mongodb
      - solr

  streammanager:
    build:
      context: stream-manager-service
    image: streammanager
    networks:
      common_network:
        aliases:
          - streammanager
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
    depends_on:
      - redis
      - mongodb
      - solr

networks:
  common_network:
